aws_region                  = "{REGION}"
site_bucket_name            = "{BUCKET_NAME}"
prefix                      = "{PREFIX}"
backend_pkg_path            = "backend_api.zip"
lambda_py_version           = "{LAMBDA_PY_VERSION}"
backend_lambda_handler      = "query_verse.lambda_handler"
loaddb_pkg_path             = "load_items_db.zip"
loaddb_lambda_handler       = "load_items_db.lambda_handler"