aws_region          = "{REGION}"
site_bucket_name    = "www.insideout.com"
prefix              = "insideout"
package_build_path  = "backend_api.zip"
lambda_py_version   = "{LAMBDA_PY_VERSION}"
lambda_handler      = "query_verse.lambda_handler"